# Generated by Django 6.0.2 on 2026-02-10 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=34)),
                ('country', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='refunds.refundrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RefundStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_status_changes', to=settings.AUTH_USER_MODEL)),
                ('refund_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='refunds.refundrequest')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['status'], name='refunds_ref_status_ea3353_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['created_at'], name='refunds_ref_created_d84d21_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequest',
            index=models.Index(fields=['user', 'created_at'], name='refunds_ref_user_id_6585b3_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequestitem',
            index=models.Index(fields=['refund_request'], name='refunds_ref_refund__9a384f_idx'),
        ),
        migrations.AddIndex(
            model_name='refundrequestitem',
            index=models.Index(fields=['sku'], name='refunds_ref_sku_e4bb85_idx'),
        ),
        migrations.AddIndex(
            model_name='refundstatushistory',
            index=models.Index(fields=['refund_request', 'changed_at'], name='refunds_ref_refund__f313b7_idx'),
        ),
    ]
